# Generated by Django 3.2 on 2021-04-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('cakeid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField(default='')),
                ('flavour', models.CharField(max_length=200)),
                ('weight', models.FloatField(default='')),
                ('ingredients', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='pic/')),
            ],
        ),
    ]
