# Generated by Django 3.2 on 2021-04-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_api', '0003_auto_20210425_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='cakeid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
