# Generated by Django 3.2 on 2021-04-26 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_api', '0004_alter_cake_cakeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcaketocart',
            name='createdat',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 12, 19, 44, 53366)),
        ),
        migrations.AddField(
            model_name='addcaketocart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
