# Generated by Django 3.2 on 2021-04-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_api', '0005_auto_20210426_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcaketocart',
            name='createdat',
        ),
        migrations.RemoveField(
            model_name='addcaketocart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='addcaketocart',
            name='name',
        ),
        migrations.RemoveField(
            model_name='addcaketocart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='addcaketocart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='addcaketocart',
            name='weight',
        ),
    ]
