# Generated by Django 3.2 on 2021-04-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_api', '0006_auto_20210426_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('phone', models.IntegerField(default='')),
                ('address', models.CharField(default='', max_length=200)),
                ('pincode', models.IntegerField(default='')),
                ('city', models.CharField(default='', max_length=200)),
                ('price', models.IntegerField(default='')),
            ],
        ),
    ]
